export const movies = [
  {
    adult: false,
    backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
    genre_ids: [16, 35, 10751, 10402],
    id: 438695,
    original_language: "en",
    original_title: "Sing 2",
    overview:
      "Buster Moon e seus amigos devem persuadir o recluso astro do rock Clay Calloway a se juntar a eles para a abertura de um novo show.",
    popularity: 9205.508,
    poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
    release_date: "2021-12-01",
    title: "Sing 2",
    video: false,
    vote_average: 8.3,
    vote_count: 883,
  },
  {
    adult: false,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker é desmascarado e não consegue mais separar sua vida normal dos grandes riscos de ser um super-herói. Quando ele pede ajuda ao Doutor Estranho, os riscos se tornam ainda mais perigosos, e o forçam a descobrir o que realmente significa ser o Homem-Aranha.",
    popularity: 7827.6,
    poster_path: "/fVzXp3NwovUlLe7fvoRynCmBPNc.jpg",
    release_date: "2021-12-15",
    title: "Homem-Aranha: Sem Volta Para Casa",
    video: false,
    vote_average: 8.4,
    vote_count: 4203,
  },
  {
    adult: false,
    backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
    genre_ids: [35, 14, 12],
    id: 425909,
    original_language: "en",
    original_title: "Ghostbusters: Afterlife",
    overview:
      "Uma mãe solteira resolve se mudar para uma pequena cidade do interior com seus filhos, e acaba descobrindo uma conexão com os Caça-Fantasmas originais e o que o seu avô deixou para trás como legado.",
    popularity: 7497.179,
    poster_path: "/719aIhGrTrJ0yzkZ806Ea4rbonV.jpg",
    release_date: "2021-11-11",
    title: "Ghostbusters: Mais Além",
    video: false,
    vote_average: 7.6,
    vote_count: 1185,
  },
  {
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 568124,
    original_language: "en",
    original_title: "Encanto",
    overview:
      "Uma garota chamada Mirabel Madrigal cresce como o único membro não mágico de sua família, que vivem escondidos em uma vibrante casa encantada nas montanhas da Colômbia.",
    popularity: 6462.935,
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    release_date: "2021-11-24",
    title: "Encanto",
    video: false,
    vote_average: 7.8,
    vote_count: 2939,
  },
  {
    adult: false,
    backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
    genre_ids: [27, 28, 878],
    id: 460458,
    original_language: "en",
    original_title: "Resident Evil: Welcome to Raccoon City",
    overview:
      "O que já foi um dia a casa da gigante farmacêutica em expansão Umbrella Corporation, Raccoon City, é agora uma cidade agonizante do meio-oeste. O êxodo da empresa transformou a cidade em um deserto, com um grande mal fermentando escondido abaixo da superfície. Quando esse mal é libertado, um grupo de sobreviventes deve trabalhar juntos para descobrir a verdade por trás da Umbrella enquanto buscam viver por mais uma noite.",
    popularity: 5472.481,
    poster_path: "/eStYYbyaxyDMzHVkGrmkiSrMi0h.jpg",
    release_date: "2021-11-24",
    title: "Resident Evil: Bem-Vindo a Raccoon City",
    video: false,
    vote_average: 6.1,
    vote_count: 882,
  },
  {
    adult: false,
    backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
    genre_ids: [878, 28, 12],
    id: 624860,
    original_language: "en",
    original_title: "The Matrix Resurrections",
    overview:
      "Em um mundo de duas realidades — a vida cotidiana e o que está por trás dela —, Thomas Anderson terá que escolher seguir o coelho branco mais uma vez. A escolha, embora seja uma ilusão, ainda é a única maneira de entrar ou sair da Matrix, que é mais forte, mais segura e mais perigosa do que nunca.",
    popularity: 4703.672,
    poster_path: "/9DT4WVqZqBEI9Kub18gZ3m1D89m.jpg",
    release_date: "2021-12-16",
    title: "Matrix Resurrections",
    video: false,
    vote_average: 6.9,
    vote_count: 2220,
  },
  {
    adult: false,
    backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    genre_ids: [878, 28, 12],
    id: 580489,
    original_language: "en",
    original_title: "Venom: Let There Be Carnage",
    overview:
      "Em busca de seu próximo furo de reportagem, o jornalista Eddie Brock consegue uma entrevista exclusiva com Cletus Kasady, um assassino no corredor da morte, que descobre o segredo de Eddie e se torna o hospedeiro de Carnificina, um simbionte aterrorizante e ameaçador. Eddie e Venom precisam superar sua relação atribulada e trabalhar em conjunto para derrotar Carnificina.",
    popularity: 3660.958,
    poster_path: "/h5UzYZquMwO9FVn15R2eK2itmHu.jpg",
    release_date: "2021-09-30",
    title: "Venom: Tempo de Carnificina",
    video: false,
    vote_average: 7.1,
    vote_count: 5838,
  },
  {
    adult: false,
    backdrop_path: "/9fzNf2QcsHVvdx5g5QUOgAWpADw.jpg",
    genre_ids: [18, 27, 9648],
    id: 516329,
    original_language: "en",
    original_title: "Antlers",
    overview:
      "Uma jovem professora descobre que o pai e irmão mais novo do seu aluno problemático escondem um segredo sobre-humano mortal. Tendo decidido tomar conta do menino, ela deve lutar pela sobrevivência dos dois contra horrores além da imaginação.",
    popularity: 2079.227,
    poster_path: "/d2c8DlW3qfu4w6fgn4lMrI6wEfM.jpg",
    release_date: "2021-10-28",
    title: "Espíritos Obscuros",
    video: false,
    vote_average: 6.4,
    vote_count: 340,
  },
  {
    adult: false,
    backdrop_path: "/1BqX34aJS5J8PefVnQSfQIEPfkl.jpg",
    genre_ids: [80, 28, 53],
    id: 826749,
    original_language: "en",
    original_title: "Fortress",
    overview:
      "A história gira em torno de um resort ultrassecreto para oficiais de inteligência aposentados dos EUA. Um grupo de criminosos liderados por Balzary rompeu o complexo, infernalmente se vingou de Robert, forçando o oficial aposentado e seu filho a salvar o dia.",
    popularity: 1646.086,
    poster_path: "/hYi00SLc8v92h5i4MoluCvIwLG1.jpg",
    release_date: "2021-12-17",
    title: "A Fortaleza",
    video: false,
    vote_average: 6.3,
    vote_count: 109,
  },
  {
    adult: false,
    backdrop_path: "/1Wlwnhn5sXUIwlxpJgWszT622PS.jpg",
    genre_ids: [16, 35, 10751],
    id: 585245,
    original_language: "en",
    original_title: "Clifford the Big Red Dog",
    overview:
      "Clifford era um pequeno filhotinho de cachorro vermelho que vivia em uma casa repleta de amor e cuidado. Porém, o amor de sua jovem dona, Emily Elizabeth, por ele é tão grande, que o cão cresce até atingir um tamanho gigantesco.",
    popularity: 1512.583,
    poster_path: "/s7Cn3OsY32tH5cyz7CHxYdEiXMn.jpg",
    release_date: "2021-11-10",
    title: "Clifford, o Gigante Cão Vermelho",
    video: false,
    vote_average: 7.4,
    vote_count: 880,
  },
  {
    adult: false,
    backdrop_path: "/mRZDHjArYNWpOv06kxRK1cduQKh.jpg",
    genre_ids: [27, 53],
    id: 754934,
    original_language: "en",
    original_title: "Son",
    overview:
      "Quando um menino contrai uma doença misteriosa, sua mãe deve decidir o quão longe ela irá para protegê-lo das forças terríveis de seu passado.",
    popularity: 1277.502,
    poster_path: "/x6QStvZ0RBahnz5YZ584yeZLb5x.jpg",
    release_date: "2021-08-06",
    title: "Herdeiro",
    video: false,
    vote_average: 6.2,
    vote_count: 67,
  },
  {
    adult: false,
    backdrop_path: "/fCdaIDKCIhsorJE30MvfxIlkqrd.jpg",
    genre_ids: [27, 9648, 53],
    id: 646385,
    original_language: "en",
    original_title: "Scream",
    overview:
      "Vinte e cinco anos após uma série de crimes brutais chocar a tranquila Woodsboro, um novo assassino se apropria da máscara de Ghostface e começa a perseguir um grupo de adolescentes para trazer à tona segredos do passado mortal da cidade.",
    popularity: 1155.714,
    poster_path: "/2PYQKeDhFwP5IX7EnIpCComBqj8.jpg",
    release_date: "2022-01-12",
    title: "Pânico",
    video: false,
    vote_average: 7.2,
    vote_count: 142,
  },
  {
    adult: false,
    backdrop_path: "/nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg",
    genre_ids: [35, 18, 878],
    id: 646380,
    original_language: "en",
    original_title: "Don't Look Up",
    overview:
      "Dois astrônomos descobrem um cometa mortal vindo em direção à Terra e partem em um tour midiático para alertar a humanidade. Só que ninguém parece dar muita bola.",
    popularity: 1093.726,
    poster_path: "/6Sc7Tjt7aPsdghYK32mDMFeZkqJ.jpg",
    release_date: "2021-12-07",
    title: "Não Olhe para Cima",
    video: false,
    vote_average: 7.3,
    vote_count: 3722,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Em um futuro distante, planetas são comandados por casas nobres que fazem parte de um império feudal intergalático. Paul Atreides é um jovem cuja família toma o controle do planeta deserto Arrakis, também conhecido como Duna. A única fonte da especiaria Melange, a substância mais importante do cosmos, Arrakis se mostra ser um planeta nem um pouco fácil de governar.",
    popularity: 1047.726,
    poster_path: "/uzERcfV2rSHNhW5eViQiO9hNiA7.jpg",
    release_date: "2021-09-15",
    title: "Duna",
    video: false,
    vote_average: 7.9,
    vote_count: 5490,
  },
  {
    adult: false,
    backdrop_path: "/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg",
    genre_ids: [12, 28, 53],
    id: 370172,
    original_language: "en",
    original_title: "No Time to Die",
    overview:
      "Bond deixou o serviço ativo e está desfrutando de uma vida tranquila na Jamaica. Sua paz é interrompida quando o seu velho amigo Felix Leiter, da CIA, aparece pedindo sua ajuda. A missão de resgatar um cientista sequestrado acaba sendo muito mais difícil do que o esperado, deixando Bond no caminho de um vilão misterioso e armado com uma nova tecnologia perigosa.",
    popularity: 1042.804,
    poster_path: "/luE0KG1rWfUptbgNtlNtL5sihyd.jpg",
    release_date: "2021-09-29",
    title: "007: Sem Tempo para Morrer",
    video: false,
    vote_average: 7.5,
    vote_count: 3165,
  },
  {
    adult: false,
    backdrop_path: "/zlj0zHo67xXoj7hvwGtaKRkSdBV.jpg",
    genre_ids: [12, 18],
    id: 728526,
    original_language: "en",
    original_title: "Encounter",
    overview:
      "Um fuzileiro naval condecorado vai em uma missão de resgate para salvar os dois filhos de uma ameaça não humana. Conforme a jornada os leva em direção ao perigo, os meninos precisam deixar a infância para trás.",
    popularity: 1004.931,
    poster_path: "/eMzpQhqcbgzKQiPEJnqVctfcKjj.jpg",
    release_date: "2021-12-03",
    title: "Encontros",
    video: false,
    vote_average: 6.3,
    vote_count: 198,
  },
  {
    adult: false,
    backdrop_path: "/5B22eed7ErxFiYAG4Ksb4eLwKNF.jpg",
    genre_ids: [16, 10751, 12, 35],
    id: 770254,
    original_language: "en",
    original_title: "Back to the Outback",
    overview:
      "Eles são perigosamente fofos! A caçada começa quando um grupo de animaizinhos letais (e um coala-celebridade chamado Pelúcio) escapa do parque onde vivem na Austrália e tentam voltar para seu lar.",
    popularity: 882.092,
    poster_path: "/9TtAmtq6iJfzh6qG4euG6eoUQDm.jpg",
    release_date: "2021-12-03",
    title: "Próxima Parada: Lar Doce Lar",
    video: false,
    vote_average: 7.8,
    vote_count: 243,
  },
  {
    adult: false,
    backdrop_path: "/kGyl8SCp9We2eTjRydqjJQJ18tg.jpg",
    genre_ids: [80, 18, 53],
    id: 656991,
    original_language: "en",
    original_title: "Wild Indian",
    overview:
      "Dois homens aprendem a lidar com um segredo traumático que compartilham sobre o assassinato selvagem de um colega de escola.",
    popularity: 861.413,
    poster_path: "/yhOpkNvgW1ZzmEpR4iqxKwKKShL.jpg",
    release_date: "2021-09-03",
    title: "Wild Indian",
    video: false,
    vote_average: 6.5,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: "/uWGPC7j70LE64nbetxQGSSYJO53.jpg",
    genre_ids: [53, 10752],
    id: 762433,
    original_language: "en",
    original_title: "Zeros and Ones",
    overview:
      "Um soldado americano estacionado em Roma com o Vaticano explodido embarca numa viagem de herói para descobrir e defender-se contra um inimigo desconhecido que ameaça o mundo inteiro.",
    popularity: 793.543,
    poster_path: "/nUklycRTVya348M5dG7JyticAsW.jpg",
    release_date: "2021-11-18",
    title: "Zero e Uns",
    video: false,
    vote_average: 5.5,
    vote_count: 101,
  },
  {
    adult: false,
    backdrop_path: "/upOi9aVqPPky7Ba4GsiyFdjc82I.jpg",
    genre_ids: [37, 28, 53],
    id: 887767,
    original_language: "fr",
    original_title: "Last Shoot Out",
    overview:
      "Neste enérgico Western protagonizado por Bruce Dern (Os Oito Odiados), um pistoleiro valente salva uma noiva em fuga - mas terá de enfrentar a ira da família enraivecida e vingativa do noivo.",
    popularity: 757.332,
    poster_path: "/4bTUK455ZQPdbHiRX1udYhdO8BH.jpg",
    release_date: "2021-12-03",
    title: "O Último Duelo",
    video: false,
    vote_average: 6.3,
    vote_count: 67,
  },
];
